"""add choice model

Revision ID: 0f6b7d0c1c8e
Revises: dbb20ead0f9d
Create Date: 2025-11-14 11:45:41.091504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6b7d0c1c8e'
down_revision: Union[str, Sequence[str], None] = 'dbb20ead0f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_user_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'session_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('idx_external_user_id', 'users', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_users_external_user_id'), 'users', ['external_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_user_id'), table_name='users')
    op.drop_index('idx_external_user_id', table_name='users')
    op.alter_column('users', 'session_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'external_user_id')
    # ### end Alembic commands ###
