"""init db

Revision ID: dbb20ead0f9d
Revises:
Create Date: 2025-11-04 14:49:53.856688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "dbb20ead0f9d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pool_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_URL", sa.Text(), nullable=False),
        sa.Column("person_code", sa.String(length=50), nullable=True),
        sa.Column("person_name", sa.String(length=100), nullable=True),
        sa.Column("person_gender", sa.String(length=20), nullable=True),
        sa.Column("person_age_range", sa.String(length=20), nullable=True),
        sa.Column(
            "face_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False
        ),
        sa.Column("face_confidence", sa.Float(), nullable=False),
        sa.Column(
            "facial_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "diversity_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("phase_eligibility", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("phase_1_priority", sa.Integer(), nullable=True),
        sa.Column("phase_2_priority", sa.Integer(), nullable=True),
        sa.Column("phase_3_priority", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("pass_count", sa.Integer(), nullable=True),
        sa.Column("prefer_count", sa.Integer(), nullable=True),
        sa.Column("avg_response_time", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("disabled_reason", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_shown_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "face_confidence >= 0 AND face_confidence <= 1",
            name="check_pool_face_confidence",
        ),
        sa.CheckConstraint(
            "phase_1_priority >= 1 AND phase_1_priority <= 10",
            name="check_phase1_priority",
        ),
        sa.CheckConstraint(
            "phase_2_priority >= 1 AND phase_2_priority <= 10",
            name="check_phase2_priority",
        ),
        sa.CheckConstraint(
            "phase_3_priority >= 1 AND phase_3_priority <= 10",
            name="check_phase3_priority",
        ),
        sa.CheckConstraint(
            "quality_score >= 0 AND quality_score <= 10", name="check_quality_score"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_URL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_token", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ONBOARDING", "ACTIVE", "COMPLETED", name="userstatus"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_users_session_token"), "users", ["session_token"], unique=True
    )
    op.create_table(
        "user_choices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("pool_image_id", sa.UUID(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=False),
        sa.Column("position_in_phase", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("LIKE", "PASS", "PREFER", name="choicetype"),
            nullable=False,
        ),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("is_revised", sa.Boolean(), nullable=True),
        sa.Column(
            "original_action",
            sa.Enum("LIKE", "PASS", "PREFER", name="choicetype"),
            nullable=True,
        ),
        sa.Column("revision_count", sa.Integer(), nullable=True),
        sa.Column("shown_with_images", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "ui_interaction", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("phase IN (1, 2, 3)", name="check_phase"),
        sa.CheckConstraint(
            "position_in_phase >= 1 AND position_in_phase <= 20", name="check_position"
        ),
        sa.CheckConstraint("response_time_ms > 0", name="check_response_time"),
        sa.ForeignKeyConstraint(
            ["pool_image_id"],
            ["pool_images.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "pool_image_id", name="unique_user_pool_image"),
    )
    op.create_table(
        "user_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_URL", sa.Text(), nullable=False),
        sa.Column(
            "face_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True
        ),
        sa.Column("face_confidence", sa.Float(), nullable=True),
        sa.Column(
            "facial_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="imagestatus"),
            nullable=True,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "face_confidence >= 0 AND face_confidence <= 1",
            name="check_face_confidence",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_images")
    op.drop_table("user_choices")
    op.drop_index(op.f("ix_users_session_token"), table_name="users")
    op.drop_table("users")
    op.drop_table("pool_images")
    # ### end Alembic commands ###
